swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /deployments:
    get:
      operationId: deployments.read_all
      tags:
        - deployments
      summary: Read the entire list of deployments
      description: Read the list of deployments
      responses:
        200:
          description: Successfully read deployment list operation
          schema:
            type: array
            items:
              properties:
                deploymentId:
                  type: integer
                application:
                  type: string
                env:
                  type: string
                status:
                  type: boolean
                notes:
                  type: string

    post:
      operationId: deployments.create
      tags:
        - deployments
      summary: Create a deployment and add it to the deployments list
      description: Create a new deployment in the deployments list
      parameters:
        - name: deployment
          in: body
          description: Deployment to create
          required: True
          schema:
            type: object
            properties:
              deploymentId:
                type: integer
                description: deploymentId
              application:
                type: string
                description: application
              env:
                type: string
                description: environment
              status:
                type: boolean
                description: status
              notes:
                type: string
                description: notes

      responses:
        201:
          description: Successfully created a deployment

  /deployments/{deploymentId}:
    get:
      operationId: deployments.read_one
      tags:
        - deployments
      summary: Read one deployment from the list
      description: Read one deployment from the list
      parameters:
        - name: deploymentId
          in: path
          description: deploymentId of the deployment to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read a deployment from the list
          schema:
            properties:
              deploymentId:
                type: integer
              application:
                type: string
              env:
                type: string
              status:
                type: boolean
              notes:
                type: string

    put:
      operationId: deployments.update
      tags:
        - deployments
      summary: Update a deployment in the list
      description: Update a deployment in the list
      parameters:
        - name: deploymentId
          in: path
          description: deploymentId of the deployment to update
          type: integer
          required: True
        - name: deployment
          in: body
          schema:
            type: object
            properties:
              application:
                type: string
              env:
                type: string
              status:
                type: boolean
              notes:
                type: string
      responses:
        200:
          description: Successfully updated a deployment

    delete:
      operationId: deployments.delete
      tags:
        - deployments
      summary: Delete a a deployment from the list
      description: Delete a deployment
      parameters:
        - name: deploymentId
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a deployment
