# This workflow will run tests when a PR is performed.
# TODO: Build, deploy and tag images
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Eagle Console - CICD Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    ### Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Extract current branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.extract_branch.outputs.branch }}
    - uses: actions/checkout@v2
      with:
        repository: tranquilitybase-io/TranquilityBase
        path: TranquilityBase
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        #repository: tranquilitybase-io/tb-eagle-console
        repository: karwootang-gft/tb-eagle-console
        path: tb-eagle-console
        fetch-depth: 0
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies and run tests
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tb-eagle-console/
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install
        npm run test
